        </section> <!--fim conteiner principal -->
        <footer class="navbar-fixed-bottom">
            <h1>Footer</h1>
        </footer>
        
        <script type="text/javascript" src="<?php echo HOME_URI; ?>vendor/components/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo HOME_URI; ?>vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo HOME_URI.VIEWS; ?>js/js-doit.js"></script>

    </body>
</html>











