<?php
if (!defined('ABSPATH'))// Evita que usuários acesse este arquivo diretamente 
    exit;
?>
<!DOCTYPE html>
<html>
    <head lang="pt-BR">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo HOME_URI . VIEWS ?>css/style-doit.css">
        <link type="text/css" rel="stylesheet" href="<?php echo HOME_URI ?>vendor/twbs/bootstrap/dist/css/bootstrap-theme.min.css">
        <link type="text/css" rel="stylesheet" href="<?php echo HOME_URI ?>vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
        <title><?php echo $this->title ?></title>
    </head>
    <body>
        <header class="conteiner navbar-fixed-top col-lg-12 ">
            <h1>Logomarca</h1>
        </header>
        <section class="conteiner-principal col-lg-8 col-xs-8 col-xs-offset-3 col-lg-offset-3"> <!--conteiner principal  -->














