<div id="wrapper" class="active col-lg-3">

    <!-- Sidebar -->
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul id="sidebar_menu" class="sidebar-nav">
            <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
        </ul>
        <ul class="sidebar-nav" id="sidebar">     
            <li><a href="<?php echo HOME_URI; ?>">Home<span class="sub_icon glyphicon glyphicon-home"></span></a></li>
            <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                <a href="#"> Exemplo<span class="sub_icon glyphicon glyphicon-link"></span></a>
            </li>
            <ul class="sub-menu collapse" id="products">
                <li class="active"><a href="<?php echo HOME_URI; ?>exemplo/">Exemplo</a></li>
                <li class="active"><a href="<?php echo HOME_URI; ?>exemplo/outra-acao/">Uma acao </a></li>

            </ul>
        </ul>
    </div>
</div>