<section>
    <div class="" style="text-align:center;">
        <h1>Pagina principal</h1>
        <h3>Esse layout só para testes!</h3>
        <blockquote>
            <q>
                Não são as nossas ideias que nos fazem otimistas ou pessimistas, 
                mas o otimismo e o pessimismo de origem fisiológica que fazem as nossas ideias.
            </q>
        </blockquote>
    </div>
</section>
